version: '3'
services:
  frontend:
## uncomment the following lines, and comment the "image" line, to use local build context (useful for development)
    build:
      context: .
      dockerfile: Dockerfile
## use following line to pull pre-built image from dockerhub (need to do it this way for deploying to Azure web app
#    image: "nbarlow/ds4sd_image_labeller:latest"
    ports:
     - "80:5000"
    environment:
     - DB_TYPE=postgres  # when deploying locally, can use custom container name
     - DB_USER=il
     - DB_PASSWORD=il
     - DB_DATABASE=img-labeller
     - DB_HOST=postgres
     - DB_PORT=5432
    depends_on:
     - postgres
    networks:
     - db_nw
  postgres:
    image: "postgres:latest"
    container_name: "postgres" # this seems to be ignored when deploying to Azure web app.
    environment:
      - POSTGRES_USER=il
      - POSTGRES_PASSWORD=il
      - POSTGRES_DB=img-labeller
    ports:
     - 5432:5432
    networks:
     - db_nw

networks:
  db_nw:
    driver: bridge